### ISSUE TITLE
Avoid counting empty lines

### ISSUE THREAD

**Issue by ghost** [alldritt/TextKit_LineNumbers#1]
Hi there!

Thanks for this great example on how to use the new Text Kit of iOS. But I'm struggling a bit around to understand what exactly is going on counting the line numbers. I have a yet simple but special need: 
Optionally don't count empty lines.

That means all lines containing just whitespaces and newlines shouldn't be counted.

Any suggestions?
Thanks a lot for sharing!

**Comment by alldritt** [comment]
NSString/NSAttributedString do not provide a built-in means of determining line numbers.  As a result, you have to count lines in some way.  My example code contains an optimization to avoid repeatedly counting lines from the beginning of the text storage.  The code counts forwards or backwards from them last known paragraph with the knowledge that scrolling operations are mostly in small increments relative to the last known range of text.

In your case, you are introducing a second attribute: the presence or absence of a line number on a given paragraph of text.  I would approach this in two stages:
1. alter the line counting code to ignore paragraphs containing only whitespace characters (space, tab, newline).  I think this test would detect paragraphs containing only whitespace within the `enumerateSubstringsInRange:options:withBlock:` block:
   
   ```
   if ([substring rangeOfCharacterFromSet:[NSCharacterSet whitespaceCharacterSet]].length == substring.length) {
       // this paragraph contains only whitespace
   }
   ```
2. devise a means of determining if a line has a line number or not (you could simply look at the paragraph text again and see if it contains anything other than whitespace).  Take care here to include the test from my code which deals with line wrapping within a paragraph of text.
